// Static fallback content — used only if DATABASE_URL / Neon isn't configured yet,
// so the site still renders during first-time setup. Once Prisma + Neon are wired up
// (see README), real data from the database takes over automatically.

export const fallbackHeroSlides: {
  id: string;
  order: number;
  eyebrow: string;
  title: string;
  body: string;
  imageId: string | null;
}[] = [
  {
    id: "s1",
    order: 0,
    imageId: null,
    eyebrow: "Câu chuyện thứ nhất — Cà phê",
    title: "Mỗi hạt cà phê là một ký ức được rang lên",
    body: "Từ những vườn arabica trên cao nguyên, CBD AI Cafe chọn lọc từng hạt để giữ trọn vị chua thanh và hậu ngọt dịu đặc trưng của vùng đất cao. Chúng tôi không chỉ pha cà phê — chúng tôi pha cả một câu chuyện.",
  },
  {
    id: "s2",
    order: 1,
    imageId: null,
    eyebrow: "Câu chuyện thứ hai — Đà Lạt",
    title: "Thành phố sương mù, nơi mọi tách cà phê bắt đầu",
    body: "Khí hậu se lạnh quanh năm, những đồi thông và thung lũng hoa là lý do vì sao cà phê Đà Lạt mang một vị đậm đà rất riêng. CBD AI Cafe mang không khí cao nguyên ấy đến gần bạn hơn, dù bạn đang ở đâu.",
  },
  {
    id: "s3",
    order: 2,
    imageId: null,
    eyebrow: "Câu chuyện thứ ba — CBD Robot",
    title: "Người bạn AI đứng sau quầy pha chế",
    body: "CBD Robot gợi ý đồ uống theo khẩu vị riêng của bạn, kể chuyện, và học cách pha một ly \"chuẩn bạn\" hơn mỗi ngày. Công nghệ đấy — nhưng vẫn ấm như một tách cà phê buổi sáng.",
  },
];

export const fallbackMenuItems: {
  id: string;
  code: string;
  name: string;
  description: string;
  priceVnd: number;
  isBestSeller: boolean;
  order: number;
  imageId: string | null;
  tags: string[];
}[] = [
  // I. Cà phê Việt Nam
  {
    id: "m1",
    code: "CBD-001",
    name: "Đen Đá K'Ho",
    description: "Đậm đà, hậu vị ngọt — nền cà phê K'Ho Arabica kết hợp Robusta.",
    priceVnd: 25000,
    isBestSeller: true,
    order: 0,
    imageId: null,
    tags: ["dam", "lanh", "truyen-thong"],
  },
  {
    id: "m2",
    code: "CBD-002",
    name: "Bạc Xỉu Lang Biang",
    description: "Nhiều sữa, thơm béo — êm dịu và dễ uống.",
    priceVnd: 37000,
    isBestSeller: true,
    order: 1,
    imageId: null,
    tags: ["nhe", "lanh", "truyen-thong"],
  },
  {
    id: "m3",
    code: "CBD-003",
    name: "Cà Phê Sữa Đá",
    description: "Cà phê Arabica/Robusta kết hợp sữa đặc, chuẩn vị cà phê phin Việt Nam.",
    priceVnd: 34000,
    isBestSeller: true,
    order: 2,
    imageId: null,
    tags: ["dam", "lanh", "truyen-thong"],
  },
  {
    id: "m4",
    code: "CBD-004",
    name: "Cà Phê Muối",
    description: "Vị mặn nhẹ, cân bằng vị cà phê — lạ miệng mà cuốn.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 3,
    imageId: null,
    tags: ["dam", "lanh", "truyen-thong"],
  },
  {
    id: "m5",
    code: "CBD-005",
    name: "Cà Phê Cốt Dừa",
    description: "Thơm ngậy cốt dừa tươi hoà cùng cà phê đậm đà.",
    priceVnd: 44000,
    isBestSeller: false,
    order: 4,
    imageId: null,
    tags: ["dam", "lanh", "truyen-thong"],
  },
  // II. Espresso Bar — Cà phê Ý
  {
    id: "m6",
    code: "CBD-006",
    name: "Espresso Single",
    description: "Chiết xuất espresso nguyên chất từ Arabica, 1 shot đậm đà.",
    priceVnd: 30000,
    isBestSeller: false,
    order: 5,
    imageId: null,
    tags: ["dam", "nong", "truyen-thong"],
  },
  {
    id: "m7",
    code: "CBD-007",
    name: "Espresso Double",
    description: "Chiết xuất espresso nguyên chất từ Arabica, 2 shot đậm đà hơn.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 6,
    imageId: null,
    tags: ["dam", "nong", "truyen-thong"],
  },
  {
    id: "m8",
    code: "CBD-008",
    name: "Americano",
    description: "Thanh tao, nhẹ nhàng — espresso pha loãng cùng nước nóng.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 7,
    imageId: null,
    tags: ["nhe", "nong", "truyen-thong"],
  },
  {
    id: "m9",
    code: "CBD-009",
    name: "Cappuccino",
    description: "Lớp bọt sữa mịn phủ trên nền espresso đậm đà.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 8,
    imageId: null,
    tags: ["nhe", "nong", "truyen-thong"],
  },
  {
    id: "m10",
    code: "CBD-010",
    name: "Latte",
    description: "Espresso hoà quyện cùng sữa tươi, có thể phục vụ nóng hoặc đá.",
    priceVnd: 47000,
    isBestSeller: false,
    order: 9,
    imageId: null,
    tags: ["nhe", "nong", "truyen-thong"],
  },
  // III. Trà & trà trái cây
  {
    id: "m11",
    code: "CBD-011",
    name: "Trà Dâu Đà Lạt",
    description: "Trà kết hợp dâu tươi Đà Lạt, thơm ngọt tự nhiên.",
    priceVnd: 40000,
    isBestSeller: true,
    order: 10,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m12",
    code: "CBD-012",
    name: "Trà Dâu Tằm",
    description: "Trà kết hợp dâu tằm, vị chua ngọt hài hoà.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 11,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m13",
    code: "CBD-013",
    name: "Trà Atiso Đỏ",
    description: "Dòng trà đặc trưng, vị chua thanh dễ chịu.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 12,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m14",
    code: "CBD-014",
    name: "Trà Bạc Hà Mật Ong",
    description: "Thanh mát, dịu nhẹ với hương bạc hà và mật ong.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 13,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m15",
    code: "CBD-015",
    name: "Trà Oolong Đào",
    description: "Ô Long đào hồng, đào hồng dầm cùng thạch trà đào hồng.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 14,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m16",
    code: "CBD-016",
    name: "Trà Oolong Vải",
    description: "Ô Long gạo rang kết hợp sữa tươi thanh trùng, thơm dịu vị vải.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 15,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m17",
    code: "CBD-017",
    name: "Trà Oolong Caramel Sữa",
    description: "Ô Long lụa đào, sữa tươi và đào hồng dầm — béo nhẹ, thơm caramel.",
    priceVnd: 50000,
    isBestSeller: false,
    order: 16,
    imageId: null,
    tags: ["dam", "lanh", "trai-cay"],
  },
  // IV. Matcha
  {
    id: "m18",
    code: "CBD-018",
    name: "Matcha Latte",
    description: "Matcha Nhật nguyên chất kết hợp sữa tươi béo nhẹ.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 17,
    imageId: null,
    tags: ["nhe", "lanh", "truyen-thong"],
  },
  {
    id: "m19",
    code: "CBD-019",
    name: "Matcha Coco",
    description: "Matcha kết hợp nước cốt dừa, thơm béo lạ miệng.",
    priceVnd: 50000,
    isBestSeller: false,
    order: 18,
    imageId: null,
    tags: ["nhe", "lanh", "truyen-thong"],
  },
  // V. Sinh tố & nước ép
  {
    id: "m20",
    code: "CBD-020",
    name: "Sinh Tố Bơ",
    description: "Bơ Đà Lạt xay mịn, béo ngậy tự nhiên.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 19,
    imageId: null,
    tags: ["dam", "lanh", "trai-cay"],
  },
  {
    id: "m21",
    code: "CBD-021",
    name: "Sinh Tố Xoài",
    description: "Xoài tươi xay mịn, chua ngọt hài hoà.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 20,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m22",
    code: "CBD-022",
    name: "Sinh Tố Dâu Tây",
    description: "Dâu tây tươi xay mịn, thơm ngọt tự nhiên.",
    priceVnd: 45000,
    isBestSeller: false,
    order: 21,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m23",
    code: "CBD-023",
    name: "Nước Ép Cam Tươi",
    description: "Cam tươi ép nguyên chất, giàu vitamin C.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 22,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m24",
    code: "CBD-024",
    name: "Nước Ép Táo",
    description: "Táo tươi ép nguyên chất, thanh mát dễ uống.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 23,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m25",
    code: "CBD-025",
    name: "Nước Ép Chanh Dây",
    description: "Chanh dây tươi ép, chua thanh sảng khoái.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 24,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m26",
    code: "CBD-026",
    name: "Nước Ép Dưa Hấu",
    description: "Dưa hấu tươi ép, mát lạnh giải nhiệt.",
    priceVnd: 30000,
    isBestSeller: false,
    order: 25,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m27",
    code: "CBD-027",
    name: "Nước Ép Dứa Mật",
    description: "Dứa mật tươi ép, ngọt thanh tự nhiên.",
    priceVnd: 40000,
    isBestSeller: false,
    order: 26,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
  {
    id: "m28",
    code: "CBD-028",
    name: "Nước Ép Cà Rốt",
    description: "Cà rốt tươi ép nguyên chất, giàu vitamin A.",
    priceVnd: 35000,
    isBestSeller: false,
    order: 27,
    imageId: null,
    tags: ["nhe", "lanh", "trai-cay"],
  },
];

export const fallbackRoadmapItems = [
  {
    id: "r1",
    period: "Quý 3 / 2026",
    title: "CBD Robot phiên bản giọng nói tiếng Việt",
    description:
      "Gọi món chỉ bằng lời — CBD Robot hiểu giọng vùng miền và gợi ý theo thời tiết trong ngày.",
    order: 0,
  },
  {
    id: "r2",
    period: "Quý 4 / 2026",
    title: "Ứng dụng đặt món & tích điểm CBD AI Cafe",
    description:
      "Đặt trước, tích điểm và nhận gợi ý đồ uống cá nhân hoá ngay trên điện thoại.",
    order: 1,
  },
  {
    id: "r3",
    period: "Quý 1 / 2027",
    title: "Góc trải nghiệm \"AI Lab Corner\"",
    description:
      "Không gian robot pha chế trực tiếp, nơi khách có thể quan sát và trò chuyện cùng CBD Robot.",
    order: 2,
  },
  {
    id: "r4",
    period: "Quý 3 / 2027",
    title: "Chuẩn hoá nguồn cà phê hữu cơ",
    description:
      "Toàn bộ chi nhánh chuyển sang chuỗi cung ứng cà phê hữu cơ đạt chuẩn từ nông trại Đà Lạt.",
    order: 3,
  },
];

export const fallbackBranches = [
  {
    id: "b1",
    name: "Đà Lạt — Trung Tâm",
    city: "Đà Lạt",
    status: "FIT_OUT" as const,
    etaLabel: "Quý 3 / 2026",
    description: "Chi nhánh chủ lực, đặt cạnh khu Hoà Bình — nơi câu chuyện CBD AI Cafe bắt đầu.",
    order: 0,
  },
  {
    id: "b2",
    name: "Hồ Chí Minh — Quận 1",
    city: "Hồ Chí Minh",
    status: "LEASING" as const,
    etaLabel: "Quý 4 / 2026",
    description: "Mang hơi thở cao nguyên đến trung tâm thành phố năng động nhất cả nước.",
    order: 1,
  },
  {
    id: "b3",
    name: "Hà Nội — Hoàn Kiếm",
    city: "Hà Nội",
    status: "PLANNING" as const,
    etaLabel: "Quý 1 / 2027",
    description: "Không gian ấm áp giữa lòng phố cổ, kết hợp nét hiện đại của CBD Robot.",
    order: 2,
  },
  {
    id: "b4",
    name: "Đà Nẵng — Ven biển",
    city: "Đà Nẵng",
    status: "SCOUTING" as const,
    etaLabel: "Quý 2 / 2027",
    description: "Điểm dừng chân mới, nơi vị cà phê cao nguyên gặp gió biển miền Trung.",
    order: 3,
  },
];
